version: '3.8'
services: 
  database: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peixeboi
      POSTGRES_DB: banco_teste
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
